### ISSUE TITLE
how to change postgres password

### ISSUE THREAD

**Issue by varmaraju** [kostiantyn-nemchenko/ansible-role-patroni#48]
My Client is asking if we want to change the postgress password via this role?. how can we change the password. while the the first time, then only we can set the password, If I change the password and re run the this role, we are not able to change the potgress password.

**Comment by kostiantyn-nemchenko** [comment]
https://github.com/kostiantyn-nemchenko/ansible-role-patroni/issues/47#issuecomment-451647514

I would suggest trying the following scenario:
1) put patroni into the maintenance mode;
2) redeploy this role with new password for postgres user;
3) resume the maintenance mode.
