### ISSUE TITLE
Deployment failure on ubuntu 18.04 with python3

### ISSUE THREAD

**Issue by litewhatever** [kostiantyn-nemchenko/ansible-role-patroni#70]
Hello

Would you consider a pull request which switches `patroni_system_packages` to python3 (`python3-psycopg2 python3-pip`) for ubuntu 18.04 but keeps them as they are for other versions (including Debian itself)?

Regards
Kristjan

**Comment by kostiantyn-nemchenko** [comment]
Hello Kristjan,

Yes, sure. Feel free to implement a PR. I would be happy to review and merge it.

**Comment by kostiantyn-nemchenko** [comment]
Closed by #71
