### ISSUE TITLE
An option to disable backup on copy tasks

### ISSUE THREAD

**Issue by daamien** [kostiantyn-nemchenko/ansible-role-patroni#77]
Hi @kostiantyn-nemchenko !

Thanks a lot for this, it is very useful.... 

I've played with the role to deploy callbacks scripts on various hosts and in the long I find that the `backup: true` option on the copy task is a bit annoying:
 
https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/tasks/configure.yml#L27

When I run the playbook several times, the destination folders is fillled with backup files which are not really useful...

Do you think we could had an option called `backup_on_copy` and let users decide if they want to keeps old version or not ?

If you agree with this idea, I can submit a PR for that.

**Comment by kostiantyn-nemchenko** [comment]
Hi @daamien !

Thank you for your interest in this project.
I like the idea and would appreciate any help you could provide to improve this role.
