### ISSUE TITLE
Callback scripts override empty files

### ISSUE THREAD

**Issue by dzubchik** [kostiantyn-nemchenko/ansible-role-patroni#80]
Hi! Thank you for this perfect role. 

We faced with a problem that after second run of playbook our callback scripts are empty, because they are overridden by this part of code - https://github.com/kostiantyn-nemchenko/ansible-role-patroni/blob/master/tasks/configure.yml#L20. 

It would be nice to have ability to change path for callback scripts. What do you think about this?

**Comment by kostiantyn-nemchenko** [comment]
Hi @dzubchik !
Could you please submit a PR to fix the issue?

**Comment by dzubchik** [comment]
@kostiantyn-nemchenko sure! Request is opened - https://github.com/kostiantyn-nemchenko/ansible-role-patroni/pull/81
