### ISSUE TITLE
Next release / patroni rest api & ssl

### ISSUE THREAD

**Issue by blogh** [kostiantyn-nemchenko/ansible-role-patroni#94]
Hi, 

We re using your playbook to deploy patroni and need to secure the rest api.
We have seen this [commit](https://github.com/kostiantyn-nemchenko/ansible-role-patroni/commit/fa6cdaecf229df7702dcfdff768684cb3bfd828a) which solves our problem and would like to use it.

Do you have a planned date to release (/ tag) this modification  ?

thank you.
Benoit

**Comment by kostiantyn-nemchenko** [comment]
Hi @blogh ,

The new version has just been released. Thank you for your interest in this project.

**Comment by blogh** [comment]
Thanks for the release !
